### ISSUE TITLE
Live typing

### ISSUE THREAD

**Issue by easrng** [veggiedefender/typing#3]
You could use a multipart mixed-replace response a la mjpeg to make the image update live.

**Comment by veggiedefender** [comment]
Sounds interesting! Do you think it would work with GitHub's [camo proxy](https://docs.github.com/en/github/authenticating-to-github/about-anonymized-image-urls)? I experimented with "streaming" GIFs frame by frame but it seems that GitHub's proxy takes the first few seconds/frames and then loops it, so you don't get the nice realtime effect.

For example, check out this GIF that displays the current time: https://hookrace.net/time.gif

Embedding it in markdown with:
```html
<img src="https://hookrace.net/time.gif">
```

produces <img src="https://hookrace.net/time.gif"> since the URL is rewritten `https://camo.githubusercontent.com/03b66dfe5f4d4d247b45717d30f9ebbba41fb815/68747470733a2f2f686f6f6b726163652e6e65742f74696d652e676966`

Note how it loops again after three seconds :(
